version: '3'
services:
  app1:
    build: .
    environment:
      - APP_NAME=Node Server 1
    ports:
      - "3001:3000"

  app2:
    build: .
    environment:
      - APP_NAME=Node Server 2
    ports:
      - "3002:3000"

  app3:
    build: .
    environment:
      - APP_NAME=Node Server 3
    ports:
      - "3003:3000"
